(cond-expand
 (chicken-4 (use henity posix))
 (chicken-5 (import (chicken process signal) henity))
 (else (error "Unsupported CHICKEN version.")))

;; Ignore sigpipe to avoid errors when canceling a progress bar
(set-signal-handler! signal/pipe void)

(unless (progress-dialog '((title "Update System Logs")
                           (text "Scanning mail logs...")
                           (percentage 0))
                         writer: (lambda ()
                                   (print 10)
                                   (sleep 1)
                                   (print "# Updating mail logs")
                                   (print 20)
                                   (sleep 1)
                                   (print "# Resetting cron jobs")
                                   (print 50)
                                   (sleep 1)
                                   (print "This line will just be ignored")
                                   (print 75)
                                   (sleep 1)
                                   (print "# Rebooting system")
                                   (print 100)
                                   (sleep 1)))
  (error-dialog '((text "Update canceled."))))
